# Generated by Django 2.2.1 on 2019-07-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicviewcontroller', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
