# Generated by Django 2.2.4 on 2019-08-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publicviewcontroller", "0008_kycmember_deleted")]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
