# Generated by Django 2.2.4 on 2019-11-05 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicviewcontroller', '0010_juniorposition_kycjuniormember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmember',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicviewcontroller.JuniorPosition'),
        ),
    ]
